export const NODE_TYPES = {
  SYSTEM_MESSAGE: 'SYSTEM_MESSAGE',
  HOST_DIALOGUE: 'HOST_DIALOGUE',
  PLAYER_CHOICE: 'PLAYER_CHOICE',
  SYSTEM_PLAYER_DIALOGUE: 'SYSTEM_PLAYER_DIALOGUE',
  SYSTEM_ACTION: 'SYSTEM_ACTION',
} as const;

export const EMOTIONS = {
  FEARFUL_WEAK: 'FEARFUL_WEAK',
  PAINED: 'PAINED',
  PAINED_HOPEFUL: 'PAINED_HOPEFUL',
  MORE_PAINED: 'MORE_PAINED',
  RELIEVED_SURPRISED: 'RELIEVED_SURPRISED',
  GRATEFUL_CURIOUS: 'GRATEFUL_CURIOUS',
} as const;

export const EFFECT_TYPES = {
  SET_VARIABLE: 'SET_VARIABLE',
  CHANGE_TRUST: 'CHANGE_TRUST',
  CHANGE_HOST_STATUS: 'CHANGE_HOST_STATUS',
} as const; 